


reset; 
 
option solver cplexamp; 
option omit_zero_rows 0; 
option display_precision 6; 
#option presolve 0; 
#option presolve_eps 10e-17; 
option cplex_options 'time=7200 bestnode threads=4'; 
  
  

model C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalModFile.mod;  
data  C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalDataFiles\DataSet1\COM1_nL15_nS100.dat; 


#specify the following model parameters in the run file
#BaseCase with default values
let kappa:=0.01*kappa_max;
let alpha:=0;
let B:=0*B;


include C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalAlternativeFormulations_COM_SelectedRLT.run; 


display Name, {i in SelectedModels} M_Time[i,4], M_OBFV, M_Bestnode, M_ResNum, com_measure1, com_measure2, kappa, alpha, B, M_Message, M_INDICATE, M_Time, M_Cost, M_Sequence,
M_Vectheta, M_Vecu
> C:\EndogenousUncertainty_Scheduling\AMPLFiles\OutputFiles\ModelAnalysis\DataSet1\COM1_nL15_nS100_kappa001_B0_alpha0.out; 






reset; 
 
option solver cplexamp; 
option omit_zero_rows 0; 
option display_precision 6; 
#option presolve 0; 
#option presolve_eps 10e-17; 
option cplex_options 'time=7200 bestnode threads=4'; 
  
  

model C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalModFile.mod;  
data  C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalDataFiles\DataSet1\COM1_nL15_nS100.dat; 


#specify the following model parameters in the run file
#BaseCase with default values
let kappa:=0.01*kappa_max;
let alpha:=0;
let B:=0.25*B;


include C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalAlternativeFormulations_COM_SelectedRLT.run; 


display Name, {i in SelectedModels} M_Time[i,4], M_OBFV, M_Bestnode, M_ResNum, com_measure1, com_measure2, kappa, alpha, B, M_Message, M_INDICATE, M_Time, M_Cost, M_Sequence,
M_Vectheta, M_Vecu
> C:\EndogenousUncertainty_Scheduling\AMPLFiles\OutputFiles\ModelAnalysis\DataSet1\COM1_nL15_nS100_kappa001_B025_alpha0.out; 






reset; 
 
option solver cplexamp; 
option omit_zero_rows 0; 
option display_precision 6; 
#option presolve 0; 
#option presolve_eps 10e-17; 
option cplex_options 'time=7200 bestnode threads=4'; 
  
  

model C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalModFile.mod;  
data  C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalDataFiles\DataSet1\COM1_nL15_nS100.dat; 


#specify the following model parameters in the run file
#BaseCase with default values
let kappa:=0.01*kappa_max;
let alpha:=0;
let B:=0.5*B;


include C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalAlternativeFormulations_COM_SelectedRLT.run; 


display Name, {i in SelectedModels} M_Time[i,4], M_OBFV, M_Bestnode, M_ResNum, com_measure1, com_measure2, kappa, alpha, B, M_Message, M_INDICATE, M_Time, M_Cost, M_Sequence,
M_Vectheta, M_Vecu
> C:\EndogenousUncertainty_Scheduling\AMPLFiles\OutputFiles\ModelAnalysis\DataSet1\COM1_nL15_nS100_kappa001_B05_alpha0.out; 








reset; 
 
option solver cplexamp; 
option omit_zero_rows 0; 
option display_precision 6; 
#option presolve 0; 
#option presolve_eps 10e-17; 
option cplex_options 'time=7200 bestnode threads=4'; 
  
  

model C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalModFile.mod;  
data  C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalDataFiles\DataSet1\COM1_nL15_nS100.dat; 


#specify the following model parameters in the run file
#BaseCase with default values
let kappa:=0.01*kappa_max;
let alpha:=0;
let B:=0.75*B;


include C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalAlternativeFormulations_COM_SelectedRLT.run; 


display Name, {i in SelectedModels} M_Time[i,4], M_OBFV, M_Bestnode, M_ResNum, com_measure1, com_measure2, kappa, alpha, B, M_Message, M_INDICATE, M_Time, M_Cost, M_Sequence,
M_Vectheta, M_Vecu
> C:\EndogenousUncertainty_Scheduling\AMPLFiles\OutputFiles\ModelAnalysis\DataSet1\COM1_nL15_nS100_kappa001_B075_alpha0.out;






reset; 
 
option solver cplexamp; 
option omit_zero_rows 0; 
option display_precision 6; 
#option presolve 0; 
#option presolve_eps 10e-17; 
option cplex_options 'time=7200 bestnode threads=4'; 
  
  

model C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalModFile.mod;  
data  C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalDataFiles\DataSet1\COM1_nL15_nS100.dat; 


#specify the following model parameters in the run file
#BaseCase with default values
let kappa:=0.01*kappa_max;
let alpha:=0;
let B:=1.25*B;


include C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalAlternativeFormulations_COM_SelectedRLT.run; 


display Name, {i in SelectedModels} M_Time[i,4], M_OBFV, M_Bestnode, M_ResNum, com_measure1, com_measure2, kappa, alpha, B, M_Message, M_INDICATE, M_Time, M_Cost, M_Sequence,
M_Vectheta, M_Vecu
> C:\EndogenousUncertainty_Scheduling\AMPLFiles\OutputFiles\ModelAnalysis\DataSet1\COM1_nL15_nS100_kappa001_B125_alpha0.out;  






reset; 
 
option solver cplexamp; 
option omit_zero_rows 0; 
option display_precision 6; 
#option presolve 0; 
#option presolve_eps 10e-17; 
option cplex_options 'time=7200 bestnode threads=4'; 
  
  

model C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalModFile.mod;  
data  C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalDataFiles\DataSet1\COM1_nL15_nS100.dat; 


#specify the following model parameters in the run file
#BaseCase with default values
let kappa:=0.01*kappa_max;
let alpha:=0;
let B:=1.5*B;


include C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalAlternativeFormulations_COM_SelectedRLT.run; 


display Name, {i in SelectedModels} M_Time[i,4], M_OBFV, M_Bestnode, M_ResNum, com_measure1, com_measure2, kappa, alpha, B, M_Message, M_INDICATE, M_Time, M_Cost, M_Sequence,
M_Vectheta, M_Vecu
> C:\EndogenousUncertainty_Scheduling\AMPLFiles\OutputFiles\ModelAnalysis\DataSet1\COM1_nL15_nS100_kappa001_B15_alpha0.out; 





reset; 
 
option solver cplexamp; 
option omit_zero_rows 0; 
option display_precision 6; 
#option presolve 0; 
#option presolve_eps 10e-17; 
option cplex_options 'time=7200 bestnode threads=4'; 
  
  

model C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalModFile.mod;  
data  C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalDataFiles\DataSet1\COM1_nL15_nS100.dat; 


#specify the following model parameters in the run file
#BaseCase with default values
let kappa:=0.01*kappa_max;
let alpha:=0;
let B:=1.75*B;


include C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalAlternativeFormulations_COM_SelectedRLT.run; 


display Name, {i in SelectedModels} M_Time[i,4], M_OBFV, M_Bestnode, M_ResNum, com_measure1, com_measure2, kappa, alpha, B, M_Message, M_INDICATE, M_Time, M_Cost, M_Sequence,
M_Vectheta, M_Vecu
> C:\EndogenousUncertainty_Scheduling\AMPLFiles\OutputFiles\ModelAnalysis\DataSet1\COM1_nL15_nS100_kappa001_B175_alpha0.out; 





reset; 
 
option solver cplexamp; 
option omit_zero_rows 0; 
option display_precision 6; 
#option presolve 0; 
#option presolve_eps 10e-17; 
option cplex_options 'time=7200 bestnode threads=4'; 
  
  

model C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalModFile.mod;  
data  C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalDataFiles\DataSet1\COM1_nL15_nS100.dat; 


#specify the following model parameters in the run file
#BaseCase with default values
let kappa:=0.01*kappa_max;
let alpha:=0;
let B:=2*B;


include C:\EndogenousUncertainty_Scheduling\AMPLFiles\FinalAlternativeFormulations_COM_SelectedRLT.run; 


display Name, {i in SelectedModels} M_Time[i,4], M_OBFV, M_Bestnode, M_ResNum, com_measure1, com_measure2, kappa, alpha, B, M_Message, M_INDICATE, M_Time, M_Cost, M_Sequence,
M_Vectheta, M_Vecu
> C:\EndogenousUncertainty_Scheduling\AMPLFiles\OutputFiles\ModelAnalysis\DataSet1\COM1_nL15_nS100_kappa001_B2_alpha0.out; 